# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_inteira', models.IntegerField(blank=True, default=1, null=True)),
                ('qnt_meia', models.PositiveIntegerField(default=0)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_adulto', models.IntegerField(default=1)),
                ('qnt_crianca', models.IntegerField(blank=True, default=0)),
                ('nome_passageiro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poltrona', models.CharField(blank=True, max_length=3, null=True)),
                ('nome_passageiro', models.CharField(max_length=200)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Poltrona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poltronas_indisponiveis', models.CharField(blank=True, max_length=500, null=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(blank=True)),
                ('qnt_passagem', models.IntegerField(blank=True)),
                ('total', models.FloatField(blank=True)),
                ('Passagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Passagem')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('Anori', 'Anori'), ('Anama', 'Anama'), ('Codajas', 'Codajas'), ('Coari', 'Coari'), ('Manaus', 'Manaus'), ('Manacapuru', 'Manaucapuru')], default='Manaus', max_length=10)),
                ('destino', models.CharField(choices=[('Anori', 'Anori'), ('Anama', 'Anama'), ('Codajas', 'Codajas'), ('Coari', 'Coari'), ('Manaus', 'Manaus'), ('Manacapuru', 'Manaucapuru')], default='Anori', max_length=10)),
                ('preco_adulto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preco_crianca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_da_viagem', models.DateField(blank=True, null=True)),
                ('porto', models.CharField(max_length=20)),
                ('foto_embarcacao', models.ImageField(upload_to='')),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao')),
            ],
        ),
        migrations.AddField(
            model_name='poltrona',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Viagem'),
        ),
        migrations.AddField(
            model_name='compra',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Viagem'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Viagem'),
        ),
    ]
