# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_adulto', models.IntegerField(default=1)),
                ('qnt_crianca', models.IntegerField()),
                ('nome_passageiro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('Anori', 'Anori'), ('Anama', 'Anama'), ('Codajas', 'Codajas'), ('Coari', 'Coari'), ('Manaus', 'Manaus'), ('Manacapuru', 'Manaucapuru')], default='Manaus', max_length=10)),
                ('destino', models.CharField(choices=[('Anori', 'Anori'), ('Anama', 'Anama'), ('Codajas', 'Codajas'), ('Coari', 'Coari'), ('Manaus', 'Manaus'), ('Manacapuru', 'Manaucapuru')], default='Anori', max_length=10)),
                ('embarcacao', models.CharField(max_length=20)),
                ('preco_adulto', models.FloatField(blank=True, null=True)),
                ('preco_crianca', models.FloatField(blank=True, null=True)),
                ('data_da_viagem', models.DateField(blank=True, null=True)),
                ('porto', models.CharField(max_length=20)),
                ('foto_embarcacao', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Viagem'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_radioanori.Compra'),
        ),
    ]
