# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_radioanori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='qnt_meia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
