# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle_Anual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.CharField(blank=True, choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Marco'), ('ABR', 'Abril'), ('MAI', 'Maio'), ('JUN', 'Junho'), ('JUL', 'Julho'), ('AGO', 'Agosto'), ('SET', 'Setembro'), ('OUT', 'Outubro'), ('NOV', '11'), ('DEZ', '12')], max_length=10, null=True)),
                ('mes', models.CharField(blank=True, max_length=10, null=True)),
                ('receita_total', models.FloatField(blank=True, null=True)),
                ('despesa_total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Controle_Arrecadacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(blank=True, null=True)),
                ('qnt_passagem', models.IntegerField(blank=True, default=0)),
                ('qnt_adulto', models.IntegerField(blank=True, default=0)),
                ('qnt_crianca', models.IntegerField(blank=True, default=0)),
                ('alimentacao', models.FloatField(blank=True, default=0, null=True)),
                ('encomendas', models.FloatField(blank=True, default=0)),
                ('outros', models.FloatField(blank=True, default=0)),
                ('total', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Controle_Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(blank=True, null=True)),
                ('qnt_combustivel', models.IntegerField(blank=True, default=0, null=True)),
                ('preco_combustivel', models.FloatField(blank=True, default=0)),
                ('total_combustivel', models.FloatField(blank=True, default=0)),
                ('tripulacao', models.FloatField(blank=True, default=0)),
                ('alimentacao', models.FloatField(blank=True, default=0)),
                ('outros', models.FloatField(blank=True, default=0)),
                ('total', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Controle_Embarcacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('proprietario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Controle_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cargo', models.CharField(max_length=15)),
                ('barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=25)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='controle_despesas',
            name='barco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao'),
        ),
        migrations.AddField(
            model_name='controle_arrecadacao',
            name='barco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao'),
        ),
        migrations.AddField(
            model_name='controle_anual',
            name='barco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao'),
        ),
    ]
