# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20180316_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controle_despesas',
            name='qnt_combustivel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
