# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20180319_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='barco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao'),
        ),
        migrations.AddField(
            model_name='tripulacao',
            name='barco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Controle_Embarcacao'),
        ),
    ]
