# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_auto_20180326_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle_arrecadacao',
            name='total',
            field=models.FloatField(blank=True, unique_for_date='data_viagem'),
        ),
        migrations.AlterField(
            model_name='controle_despesas',
            name='total',
            field=models.FloatField(blank=True, unique_for_date='data_viagem'),
        ),
    ]
