# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_auto_20180405_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controle_arrecadacao',
            unique_together=set([('data_viagem',)]),
        ),
    ]
