# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_auto_20180408_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle_embarcacao',
            name='preco_passagem_inteira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controle_embarcacao',
            name='preco_passagem_meia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
